### ISSUE TITLE
2016年度の新入生に向けた広報活動

### ISSUE THREAD

**Issue by mugifly** [odentools/odentools#1]
2016年の新入生に対して，OdenTools および バス時刻表の利用促進ができればと考えております．

T学科だけでも良いですので，学科からそういった機会における協力を仰ぐことは可能でしょうか？

**Comment by mugifly** [comment]
> 入学式に、部活動がビラ配ってると思うので、そこに参加するのもありかと思います。
> by @ht12a092 via Slack

入学式は 2016/04/05 (火) ですね．そう考えますと，あまり時間がないですね．

タスクと期日は以下のような感じでしょうか．
2016/04/04 訂正: リーフレットは外注ではなく大学の印刷機あるいは輪転機を使用させていただくこととなりました。
- [x] 入学式当日のスクールバス，近鉄バスの時刻表入手　〜2016/03/31 (木)
- [x] リーフレットのデザイン一次案　〜2016/04/01 (金)
- [x] リーフレットの印刷　〜2016/04/04 (月)
- [x] 時刻表データの登録　〜2016/04/04 (月)

@ht12a092 時刻表の入手は可能でしょうか？ また来場者数は何人くらいでしょうか？

**Comment by d-yano** [comment]
当日のダイヤについて，31日学校に確認してきます．

**Comment by mkoeda** [comment]
4/11か4/18の4限のスタディスキルで時間取りますので、お願いします。

**Comment by mugifly** [comment]
@mkoeda ありがとうございます！
それではスタディスキルで宣伝させていただきます．

また，入学式当日のサークル/委員会によるビラ配布が行われますが，その場で私たちもリーフレットを配布しようと考えております．

**Comment by d-yano** [comment]
寝屋川キャンパスにて，時刻表が貼りだされていましたのので，スクールバスについてはこちらを利用出来ると思います．

![img_9061](https://cloud.githubusercontent.com/assets/11460169/14166676/6f5526f4-f750-11e5-98b4-1b263ce7f86e.JPG)
![img_9063](https://cloud.githubusercontent.com/assets/11460169/14166677/6f55d6da-f750-11e5-8750-45b6e0ab5e59.JPG)
![img_9066](https://cloud.githubusercontent.com/assets/11460169/14166678/6f59f79c-f750-11e5-9d86-791db1bf4b8d.JPG)

**Comment by d-yano** [comment]
近鉄バスについては，営業所に確認しましたが，担当者不在との事でしたので，明日4/1に再度ご連絡・確認致します

**Comment by d-yano** [comment]
参考までに通常期のダイヤを以下に示します．  
http://www.kintetsu-bus.co.jp/search/pdf/242_1410183330.pdf

**Comment by mugifly** [comment]
作成したリーフレットをアップしておきます。あまり時間がとれませんでした（＾＾;)

https://github.com/odentools/odentools-goods/blob/master/leaflet/201604mo/leaflet.pdf

**Comment by mkoeda** [comment]
白黒で良ければ，こちらで印刷しますよ．

**Comment by mugifly** [comment]
リーフレットのデータを変更しました．
2016/04/04 16;49 訂正: すみません．QRコードに誤りがあったため，現在修正中です．

今回，業者さんへの印刷外注は行わないこととなりましたので，データ上の余白は削除しました．
また塗り足しやトンボなども設定してありません．
これにより，A4サイズ 片面モノクロ ふちなしとなっています．

実際にはふちなし非対応の印刷機で印刷し，断裁加工も行わないこととなるかと思いますので，
ふちありで構いませんが，なるべく塗りの欠落が発生しないようリサイズして印刷します．

**Comment by mugifly** [comment]
データを差し替えてタグ (20160405-entrance-ceremony) をつけておきました．
https://github.com/odentools/odentools-goods/blob/20160405-entrance-ceremony/leaflet/201604mo/leaflet.pdf

**Comment by ht12a092** [comment]
@mugifly 確認しました！良いデザインですね．これで行きましょう．
@mkoeda 
>白黒で良ければ，こちらで印刷しますよ．
ありがとうございます！
研究室のプリンターで印刷しても良いということでしょうか？

**Comment by mkoeda** [comment]
＞研究室のプリンターで印刷しても良いということでしょうか？

いや，研究室のプリンタではなく，学校のプリンタを使って講義資料として印刷します．



2016-04-04 17:32 GMT+09:00 Daiki Yano <notifications@github.com>:

> @mugifly <https://github.com/mugifly> 確認しました！良いデザインですね．これで行きましょう．
> @mkoeda <https://github.com/mkoeda>
>
> 白黒で良ければ，こちらで印刷しますよ．
> ありがとうございます！
> 研究室のプリンターで印刷しても良いということでしょうか？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/odentools/odentools/issues/1#issuecomment-205194123>
>



-- 
Masanao KOEDA (Associate Professor)
Osaka Electro-Communication University,
Faculty of Information Science and Arts, Department of Computer Science
Kiyotaki 1130-70, Shijonawate, Osaka, 575-0063, JAPAN
Main / Personal TEL: +81-72-876-3317 / +81-72-876-5417
URL: http://www.cs-oecu.jp/   http://opencv.jp/

**Comment by mugifly** [comment]
なるほど．たしかにスタディスキルの講義資料ということですからね．

**Comment by mugifly** [comment]
@mkoeda 入学式当日朝の印刷は可能ですか？

**Comment by mkoeda** [comment]
なるほど，明日，配りたいのね．
２００部印刷して，1-218に置いておきました．
輪転機なので，クオリティは期待しないでね．
（QRコードは読めました．）

**Comment by mugifly** [comment]
@mkoeda なんと！ありがとうございます！！！
大変お手数おかけいたしました．助かりました．

**Comment by mugifly** [comment]
@ht12a092 明日のダイヤって登録済みでしたよね？一応確認です．

**Comment by d-yano** [comment]
@mugifly 今晩登録しておきます！

**Comment by d-yano** [comment]
入学式当日からの特別ダイヤです．

[2016年度_入学式&オリエンテーションバスダイヤ.pdf](https://github.com/odentools/odentools/files/202697/2016._.pdf)

**Comment by d-yano** [comment]
@mkoeda ありがとうございます！

**Comment by d-yano** [comment]
@mugifly 4/5ダイヤの登録を行い，サイネージの再起動をしました．

**Comment by mugifly** [comment]
入学式における広報活動，計350枚程度配布できました．皆さまお疲れ様でした．

また，スタディスキルの授業中における広報活動については，授業資料として以下のリポジトリを作成しました．
https://github.com/odentools/interactive-comm-book
