### ISSUE TITLE
時刻表サイネージのSDカード交換

### ISSUE THREAD

**Issue by mugifly** [odentools/odentools#2]
大学に設置されている時刻表サイネージに不具合が発生しているとのことで，SDカードのファイルシステム破損が考えられるため，カード交換を行います．

2016/03/30 現在，管理画面から不具合が認められるサイネージは，四條畷キャンパス 1号館設置の物のみです．

寝屋川キャンパス A号館のサイネージの状態については，2016/03/31 に @ht12a092 が確認予定です．

**Comment by d-yano** [comment]
@mugifly 寝屋川キャンパス無事動作確認しました．
お手数をおかけいたしました．

**Comment by mugifly** [comment]
@ht12a092 ありがとうございます！よかったです！

**Comment by mugifly** [comment]
四條畷1号館サイネージのSDカードについて，余っているカードが見当たらなかったため，同一のものに焼き直しを行いました
．
これにより，時刻表が正常に表示されること および 管理画面にデバイスが表示されることを確認しました．
