### ISSUE TITLE
新入生向け勉強会の開催

### ISSUE THREAD

**Issue by d-yano** [odentools/odentools#3]
新入生向けにWeb勉強会的なものをしたいです．
詳細は議論していきましょう

キーワード：
4月ぐらい　実際に遊べるような

例）GPSを使った鬼ごっことか
初めに昨日の説明とかをして，少しHTMLのデザインをする．
その後，ｈｅｒｏｋｕとかで動かして遊ぶとか？ｗ

**Comment by mugifly** [comment]
新入生といえばうちの今の1年生ははまずProcessingに触れますから、Processingでなにかやりますか？

**Comment by mugifly** [comment]
複数人のチームを組んで行う形式のほうが良いですかね．
1人ずつで行うより助けあいやすいと思いますし，もしチームの中に少しでも詳しい人がいれば，運営側のサポートの大変さが減るかもしれません．

**Comment by mugifly** [comment]
「もしチームの中に少しでも詳しい人がいれば」と書きましたが，あえてチームを運営側で組んでしまうのもありかもしれません．
募集と一緒に簡単なプロフィール(自己紹介とスキルレベル)を書いてもらって，チーム編成の参考情報とする感じです．

例えば，某委員会が大学で実施している新入生歓迎祭でも，
各グループのメンバーは運営側が勝手に決めています．
1人で参加している人のほうが圧倒的多数ですし，全く知らない人やバックグラウンドの異なる人とコミュニケーションをとる機会を設けるためです．

さらにイベント中のゲームでグループをシャッフルさせて，さらなる繋がりを促進したりもしますが．

**Comment by d-yano** [comment]
なるほど！
かなりゲーム性があって面白そうですね．

> 各グループのメンバーは運営側が勝手に決めています

確かにこれなら勉強会の中で，技術を学ぶだけではなく，沢山の交流が出来る形に出来ますね．

**Comment by mugifly** [comment]
2016年6月の合宿を以ってこれに代えさせていただきます．
