### ISSUE TITLE
バス時刻表 - オリエンテーションダイヤの登録 (2016/04/06〜04/08)

### ISSUE THREAD

**Issue by mugifly** [odentools/odentools#5]
https://github.com/odentools/odentools/issues/1 にて入学式当日(2016/04/05)のダイヤを登録しましたが，オリエンテーションダイヤの登録が未だなのでIssueを作っておきます．

**Comment by d-yano** [comment]
2016/04/06〜04/08までのオリエンテーションダイヤを添付ファイルとしてアップロードします．
[2016年度_入学式&オリエンテーションバスダイヤ.pdf](https://github.com/odentools/odentools/files/202817/2016._.pdf)

**Comment by mugifly** [comment]
近鉄バスさんの04/09 (土)のダイヤが不明だそうです．それ以外は @ht12a092 が登録済みです．
