### ISSUE TITLE
広報 - OSC Kyoto 2016 出展

### ISSUE THREAD

**Issue by mugifly** [odentools/odentools#7]
http://www.ospn.jp/osc2016-kyoto/
- 開催日: 7月29日 & 30日
- 募集締め切り: 5月30日

**Comment by d-yano** [comment]
1) 出展(団体)名
2) URL
3) ご連絡先メールアドレス
4) 出展希望：セミナーのみ、展示のみ、セミナーと展示
5) 出展されるセミナー・展示の概要 (簡潔に)300文字程度

**Comment by d-yano** [comment]
出店の概要を考えてみました．
@mugifly 確認をお願いします．

近年，通信を行うアプリケーション開発は容易に実装でき，組み込み機器ではSerial通信，WebシステムではWebSocketやAPIなどが多く利用されています．
しかしながら，アーキテクチャーが異なるこれらのシステムで同じような実装を行う場合や，系統の同じようなアプリケーションを作る際には，車輪の再発明があると思います．
そこで今回，SQLのスキーマ定義に近い文法で，値の定義と検証ができるインタラクティブな通信フレームワークを作成しました．
展示としてこのフレームワークの紹介と同システムを用いてプログラムを作成したラジコンカーの走行デモを行いたいと思います．
ラジコンカーのデモは実機の持ち込み，フレームワークの紹介はポスター展示により行いたいと考えています．

**Comment by mugifly** [comment]
応募完了しました．
